.TH GHOPS 1 "June 2026" "ghops v1.0.0" "User Commands"
.SH NAME
ghops \- GitHub Multi\-Repo Secret Manager
.SH SYNOPSIS
.B ghops
[\fI\,-h\/\fR] [\fI\,-v\/\fR]
.SH DESCRIPTION
Interactively select GitHub repositories and set secrets across all of them in bulk.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit
.TP
.B \-v, \-\-version
Show version information and exit
.SH DEPENDENCIES
.B gh
(GitHub CLI) must be installed and authenticated.
.SH EXAMPLES
.TP
Run the interactive secret manager:
.B ghops
.SH AUTHOR
danukaji
.SH BUGS
Report bugs at https://github.com/danukaji/ghops/issues
.SH LICENSE
MIT
